FROM node:14.17.1-buster-slim

RUN  apt-get update \
     && apt-get -y install git \
     && apt-get install -y wget gnupg ca-certificates procps libxss1 \
     && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
     && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
     && apt-get update \
     && apt-get install -y google-chrome-stable \
     && rm -rf /var/lib/apt/lists/* \
     && wget --quiet https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/sbin/wait-for-it.sh \
     && chmod +x /usr/sbin/wait-for-it.sh

ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_x86_64 /usr/local/bin/dumb-init

RUN chmod +x /usr/local/bin/dumb-init

ENTRYPOINT ["dumb-init", "--"]

RUN git clone https://github.com/WayneChang65/popcat-click-it.git /usr/src/app/popcat-click-it \
    && cd /usr/src/app/popcat-click-it && npm install

WORKDIR /usr/src/app/popcat-click-it

#CMD ["node", "index.js", "high"]
CMD ["sh", "-c", "node index.js high"]
